### ISSUE TITLE
Add themeable variables for terra-overlay

### ISSUE THREAD

**Issue by jeffmerten** [cerner/terra-core#1184]
# Issue Description
Styles like the background color and opacity for the overlays are not themeable, unlike other components like the list, table, alert, etc..

## Issue Type
- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Attributes like opacity, background, and color should leverage css variables with defaults set through var().

## Current Behavior
Attributes like opacity, background, and color can't be customized, and this causes some obvious theming discrepancies between our terra and legacy sections when they are on the same page.

Terra version:
![allergies loading terra](https://user-images.githubusercontent.com/34603098/35578805-b9fa0354-05aa-11e8-857e-af2d9f99e08d.png)

Legacy Version:
<img width="1264" alt="allergies loading legacy" src="https://user-images.githubusercontent.com/34603098/35578802-b806cbe0-05aa-11e8-9a77-f39cbc3e2e26.png">

## Environment
* Component Version: terra-overlay 1.16.0
* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile): any

**Comment by paku-sruti** [comment]
# Tech Design

Replace the following in Overlay.scss: 
```css

  .dark {
    background: rgba(28, 31, 33, 0.85);
  }
```
and 

```css
  .light {
    background: rgba(244, 244, 244, 0.7);
  }
```

With the following:

```css
  .dark {
    background: var(--terra-overlay-dark-background-color, #1c1f21);
    opacity: var(--terra-overlay-dark-opacity, 0.85);
  }
```
and 

```css
  .light {
    background: var(--terra-overlay-light-background-color, #1c1f21);
    opacity: var(--terra-overlay-light-opacity, 0.7);
  }
```
