### ISSUE TITLE
Add theming property to base for background images

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1200]
# Issue Description
Add ability to theme background-image style on the body element

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Ability to theme background-image style on the body element

## Current Behavior
N/A

**Comment by bjankord** [comment]
# Tech Design

Add the following to terra-base scss file.

```css
body {
  // stylelint-disable order/properties-alphabetical-order
  background-image: var(--terra-base-background-image, none);
  background-color: var(--terra-base-background-color, #fff);
  // stylelint-enable order/properties-alphabetical-order
}
```
