### ISSUE TITLE
Ensure component links account for base link styles

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#1215]
# Issue Description
All links now include the following styles:

```css
a {
  background-color: transparent; /* Remove the gray background on active links in IE 10. */
  color: var(--terra-link-color, #0065a3);
  outline: none;
  text-decoration: underline;
}

a:visited {
  color: var(--terra-link-visted-color, #0065a3);
}

a:hover {
  color: var(--terra-link-hover-color, #004c76);
}

a:focus {
  background-color: var(--terra-link-focus-background-color, transparent);
  border-radius: var(--terra-link-focus-border-radius, 0.2142rem);
  box-shadow: var(--terra-link-focus-box-shadow, 0 0 1px 3px rgba(76, 178, 233, 0.5), 0 0 7px 4px rgba(76, 178, 233, 0.35));
  color: var(--terra-link-focus-color, #004c76);
}

a:active {
  color: var(--terra-link-active-color, #004c76);
}
```

With this, we need to look at places where we use anchors in our components, and ensure the link pseudo classes of those different components account for this new set of base styles. [This issue](https://github.com/cerner/terra-core/issues/1212) is an example of a component where the base styles of `a:visited` conflicts with our intended styles. To fix that issue, we need to update styles for button when it renders as an anchor to account for the base `a:visited` styles.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Component with anchors render correctly with new base link styles

## Current Behavior
Components with anchors render incorrectly in the link pseudo classes with the new base link styles

## Steps to Reproduce

1. Create a terra button component with an href
1. Visit the link
1. Go back to original page to see new text color

## Environment

* Component Version: Not completely sure, but I believe its the Terra-Base (version 2.11.0)
* Browser Name and Version: Chrome Version 63.0.3239.132 & Firefox 58.0.1 (64-bit)
* Operating System and version (desktop or mobile): macOS Sierra Version 10.12.6 (desktop)
