### ISSUE TITLE
Theme Versioning Proposal

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-core#1967]
# Theme Versioning

## Issue
Applications that transitively consume multiple versions of terra components are unable to reconcile theme variables.

## Proposal
Version each theme property with the major version of the component.

### Example:

terra-button - v3.0.0

`terra-button-v3-background-color`

## Strategy
To enforce theme versioning a custom lint rule should be added into stylelint-config-terra. An example of the new rule can be found [here](https://github.com/cerner/stylelint-config-terra/compare/CustomLintVersion).

This rule requires each custom property to include the package name and component version.

For passivity the new rule can have severity set to warning during the uplift and be changed to throw an error when all the initial warnings are satisfied.

## Advantages
* Applications can simultaneously theme multiple versions of a component
* Aggregated theme libraries can passively add new theme versions on a component per component basis without requiring a major version bump of the entire package

## Disadvantages
* Each major version bump will require a new set of theme variables
* Because of how lerna handles releases the package.json version is bumped after lint has run, this requires awareness of major version bumps before hand to not release the wrong set of theme variables

## Additional Changes
As part of this change there is an opportunity to standardize the custom property pattern and enforce it with the lint rule. Here are a couple possible patterns.

(package-name)-(version)-(identifier+)$
(package-name)-(version)-(identifier+)-(pseudo selector?)-(property-name)$

**Comment by bjankord** [comment]
+1

**Comment by StephenEsser** [comment]
I've added an Additional Changes section for discussion regarding whether or not to enforce a more strict naming convention of custom property names.

**Comment by bjankord** [comment]
I lean towards `(package-name)-(version)-(identifier+)$`

**Comment by mjhenkes** [comment]
+1

**Comment by benbcai** [comment]
+1

**Comment by emilyrohrbough** [comment]
+1 looks good

**Comment by neilpfeiffer** [comment]
+1:  (namespaced-package-name)-(version)-(identifier+)-(pseudo selectors)-(property-name)$

And if using classes in place of pseudo selectors/state modifiers, best practice recommendation will be to include them in the (identifier+) node.

**Comment by mhemesath** [comment]
What's an example of the current approach not working?   While this is simple to reason about with a single component, this gets more complex when defining a theme for a suite of applications. 

* Which version of variables is the theme configured to?
* How do we migrate existing themes defined in configuration?
* How does a tool allowing configuration of themes know which version to use?

**Comment by StephenEsser** [comment]
> What's an example of the current approach not working? 

Select `version 3` used `--terra-select-option-selected-color` to determine the `background-color` of a selected option. https://github.com/cerner/terra-core/blob/26d1abc138c571f78e1def38280a433a3cbf317c/packages/terra-form-select/src/SelectOption.scss#L22

Select `version 4` used `--terra-select-option-selected-color` to set the text `color` of a selected option. https://github.com/cerner/terra-core/blob/9a61ec466c4d68504f69f9e674d922ecac2769a2/packages/terra-form-select/src/_Option.module.scss#L24

`Application A` was consuming `version 3` and `version 4` with the same theme resulting in both version of the component displaying incorrectly.

> Which version of variables is the theme configured to?

There should be a theme for each version of a component.

> How do we migrate existing themes defined in configuration?

Existing themes should be updated with versioning. 1 theme for each version after this change. Most components will only have 1 version.

> How does a tool allowing configuration of themes know which version to use?

Eventually we plan to optimize theme repositories to analyze the node modules and only consume the necessary version of each theme for each component. In general I don't think there will be many versions of each theme.

Without versioning it is not possible for a single monolithic theme repository to be reliably consumed by an application that may consume multiple versions of the same component. 

With versioning a monolithic theme repository can provide all versions of a theme for a component and allow an application to consume multiple versions of the same component.

**Comment by mhemesath** [comment]
This is a result of poor variable naming.  Specificity in naming would resolve this better than versioning in this specific case. For example: `--terra-select-option-selected-color` should be `--terra-select-option-selected-backgroundcolor` because that is what it is setting.. not the color. 

IMO, more thought needs to go into the variable names to ensure they are specific to what they are doing.  Versioning will introduce a lot of complexity for client tooling to customize themes as well as terra development to analyze necessary themes. 

> Without versioning it is not possible for a single monolithic theme repository to be reliably consumed by an application that may consume multiple versions of the same component.

Yes it is possible. The property name IS the contact and we avoid breaking it at all costs.  `--terra-select-option-selected-color`  did not do what the name implied which is what cause that issue. If it were done correctly, `--terra-select-option-selected-color` would always set the option selected text color no matter what vesion of the component is being consumed. The *text color is always the text color*.

**Comment by mhemesath** [comment]
```
Versioning does introduce additional complexity, but it is the only way to resolve conflicts when they arise. Conflicts are rare, but they are present and usually are not found early enough to resolve the issue with variable naming without breaking other teams or major version bumping a component which creates the same theme versioning conflict.
```

So we're admitting that this is a rare occurrence that we're solving with the nuclear option that will make the use case of higher-order custom themes impossible to manage, map and maintain.  Any themes not applied automatically using a prebuilt theme will break when a component updates.  The theming strategy was conceived with client theming in mind and this is an incredibly non-passive and not taking that use case into consideration at all. This solution to tooling is not practical:

> The tool should analyze the available theme variables on the page or within the bundle. This would allow theming a single version or multiple versions of a component. The tool could obscure the version of each variable if necessary. 

If a tool can safely map a single variable to different versioned variables *then why can't we just do this in code* and abstract it from the consumers.  I would like to see terra move in the direction of using better property naming and stronger tests to find theme regressions before making this massive change.

**Comment by StephenEsser** [comment]
> this is an incredibly non-passive
 
Versioning the themes behind major versions of components is passive. If you major version bump the component a new version of the theme is created. They are protected behind major version bumps of the component.

> This solution to tooling is not practical:

How does the tool work today? If the tool is not analyzing the variables available on the page / bundle then they are being statically set. Statically set variables do not account for changes or versions. Variables are added and removed regularly within components. This tool would end up having variables that don't work because they were removed, would be missing variables that were added, and after the lint changes it would have variables that don't exist.

At the end of the day we need a solution that allows a single monolithic theme repository to work for multiple versions of a component.  If we enforce the lint rules above and develop stronger naming conventions then theme versioning will not be as necessary, but it does mean older versions of components will cause conflicts. The theme repositories will need to specifically indicate starting at what version of each component they theme.

**Comment by bjankord** [comment]
I'd like to collect concerns / problems / issues we are trying to solve. Let me know if there are others to add to the list.

Here are the ones I'm aware of:

a. Components use same variable name with 2 or more different values.
```css
a {
  /*    Custom Property ↓             ↓ Value    */
  color: var(--terra-example-color, #000);
}
 .anchor {
  /*    Custom Property ↓             ↓ Value    */
  color: var(--terra-example-color, #111);
}
```

b. Component use a variable name that doesn't match the CSS property
```css
a {
  /*    Custom Property ↓             ↓ Value    */
  background-color: var(--terra-example-color, #000);
}
```

c. Component changes the way a variable is used

c1. UX decideds border should be different between horizontal and vertical where before it was uniform
```css
// Old version
.foo {
  /*    Custom Property ↓             ↓ Value    */
  border: var(--terra-example-border, 5px);
}
// Changes to
// New version
.foo {
  /*    Custom Property ↓             ↓ Value    */
  border-top: var(--terra-example-border-top, 3px);
  border-bottom: var(--terra-example-border-bottom, 3px);
  border-left: var(--terra-example-border-left, 7px);
  border-right: var(--terra-example-border-right, 7px);
}
```
c2. UX decideds border should be uniform where before it was different between horizontal and vertical
```css
// Old version
.foo {
  /*    Custom Property ↓             ↓ Value    */
  border-top: var(--terra-example-border-top, 3px);
  border-bottom: var(--terra-example-border-bottom, 3px);
  border-left: var(--terra-example-border-left, 7px);
  border-right: var(--terra-example-border-right, 7px);
}
// Changes to
// New version
.foo {
  /*    Custom Property ↓             ↓ Value    */
  border: var(--terra-example-border, 5px);
}
```

d. Component removes a variable.
```css
// Old version
.icon {
  display: inline-block;
  margin-top: var(--terra-example-margin-top: 3px);
}
// Changes to
// New version
.icon {
  display: inline-block;
}
```

e. Component adds a variable
```css
// Old version
.icon {
  display: inline-block;
}
// Changes to
// New version
.icon {
  display: inline-block;
   margin-top: var(--terra-example-margin-top: 3px;
}
```

f. Client interfaces with versioned variables
```css
// Client CSS
:root {
 --terra-example-color: #f00;
}
```

```css
// Cerner Application CSS
.example {
  color: var(--terra-example-v1-color, #000);
}
```

**Comment by bjankord** [comment]
I think `a.` and `b.` can be mitigated with stylelint rules, @StephenEsser has [some of these in place](https://github.com/cerner/stylelint-config-terra/tree/master/lib/rules). 

In regards to `c1.` and `c2.`, my thoughts are maybe always writing long-hand CSS properties is best. This way it doesn't matter if they all need to be the same value or different for horizontal and vertical.

In regards to `d.`, I see this as passive so long as the visuals stay the same. I'm thinking of an instance where margin-top is used to vertically center and switch to an implementation to use flexbox for vertical center where margin-top is no longer neccesary. One issue I see with this is people including variables that are no longer used in components.

In regards to `e.`, my thoughts are this is could be a non-passive change, for example if we add a color / background color, that could cause issues in themes like the low light theme.

In regards to `f.`, my thoughts are this is a passive change so long as the variable fallback is the same as it was prior to making it a theme variable.

In regards to `g.` I see two options. Remove the version number from the theme variable name or add an abstraction layer between client theme and terra theme.
```css
// Client CSS
:root {
 --cerner-example-color: #f00;
}

// Abstraction layer
:root {
 --terra-example-v1-color: --cerner-example-color;
}

// Cerner Application CSS
.example {
  color: var(--terra-example-v1-color, #000);
}
```

**Comment by bjankord** [comment]
Abstraction layer would have to expand for all major versions of a variable:

```
// Abstraction layer
:root {
 --terra-example-v1-color: --cerner-example-color;
 --terra-example-v2-color: --cerner-example-color;
 --terra-example-v3-color: --cerner-example-color;
 --terra-example-v4-color: --cerner-example-color;
   etc....
}

**Comment by mjhenkes** [comment]
**Proposal**
Version each theme variable independently as needed.

Example:
For the terra select example where the `--terra-select-option-selected-color` variable was reused for a different intent. With this proposal the variable would be renamed:`--terra-select-option-selected-color-v1`

So the lifecycle of a normal variable would be:
The variable starts off un-versioned
`--terra-button-color`
Then if color is co-opted to mean something else the variable would be changed to:
`--terra-button-color-v1`
If its intent changes again it would be named:
`--terra-button-color-v1` 

Pros: 
Variables don't change versions unless there is a conflict.
Gives us a standard way to address version conflicts without resorting to non standard naming.

Cons: 
Versioning is reactionary and hard to test for. An issue may be found and a .1 version may need to be released with the updated versioned variable name.
The theme variables are difficult to relate to a version of a component.

**Comment by mhemesath** [comment]
I much prefer the versioning variables as needed. I will say that we should also strive to use versioning as a last resort. For example with the code above, we could do this

```css
// select v4
&.is-selected {
  background-color: var(--terra-select-option-selected-background-color, #0079be);
  color: var(--terra-select-option-selected-color, #fff);
  color: var(--terra-select-option-selected-font-color);
}
```
Supporting the old property as a passivity layer until its safe to remove it.  When versioning is required, I'd like that we only support a versioned variable for a 1 or 2 major releases before it becomes un-versioned again. This will prevent a situation where we have all  different variable versions.   Also, an alternative to versioning the variables is to scope them. For example see https://codepen.io/anon/pen/LXgjoa


Having scoped properties I think works using  https://www.npmjs.com/package/postcss-css-variables#caveats. This would allow us to not change variable names and delete versioned scopes once they are no longer of concern. Not sure this is 100% bullet proof but it does address the example above.

**Comment by bjankord** [comment]
I looked through the alernative proposal and I tested [postcss-css-variables]( https://www.npmjs.com/package/postcss-css-variables) plugin and it seems to be a passive change to swap out. It can compile the variables the same as [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) with the addition of scoping variables under selectors other than `:root`. 

A concern I see with the proposed alterntive @mhemesath is that I belive it will require theme authors to use the selector with the version class name on it in their theme definition file. For example, in the [codepen demo](https://codepen.io/anon/pen/LXgjoa), it seems a theme author would have to use `.v4 .is-selected-xyz` to set the value for `--terra-select-option-selected-color` in their theme file.  

If `v4 .is-selected-xyz` only exists in the component's CSS, I'm not sure how a theme author would customize the value of `--terra-select-option-selected-color`.  I also think this would be more challenging to document how to use theme variables if we need to note using specific selectors to target versions. 

Using only CSS custom properties, and versioning them if there is a conflict, it will be easier to aggregate the theming variables for documentation purposes. I like the idea that we should also strive to use versioning as a last resort. I think if/when there are conflicts with css custom properties, we should look at ways to avoid introdcing a version number if we can make it work like the example @mhemesath posted.

```
// select v4
&.is-selected {
  background-color: var(--terra-select-option-selected-background-color, #0079be);
  color: var(--terra-select-option-selected-color, #fff);
  color: var(--terra-select-option-selected-font-color);
}
```
Based on that, I think we should move forward with [the proposal noted here](https://github.com/cerner/terra-core/issues/1967#issuecomment-442232599).

**Comment by mhemesath** [comment]
> A concern I see with the proposed alterntive @mhemesath is that I belive it will require theme authors to use the selector with the version class name on it in their theme definition file.

Good point, probalby have the scope be something like

```css
.terra-button-v4 {
  --terra-button-color: red;
}
```
