### ISSUE TITLE
[terra-form-input] Placeholder text styling incorrect in IE11

### ISSUE THREAD

**Issue by jeremyfuksa** [cerner/terra-core#2198]
# Bug Report

## Description
In IE11, placeholder text in a form input is rendering as black text, rather than gray.
https://engineering.cerner.com/terra-ui/#/components/terra-form-input/form-input/input

## Steps to Reproduce
1. View a form input in IE11.

## Expected Behavior
Placeholder text should appear to be faded.

## Possible Solution
Ensure browser-specific styling for placeholder text is correct.

## Environment

* Component Name and Version: latest
* Browser Name and Version: IE11
* Operating System and version (desktop or mobile): Windows 10

**Comment by supreethmr** [comment]
I found that this issue of placeholder color exists in other components too like terra-text-area and terra-form-select and all this components holds style for placeholder (::placeholder pseudo element)..

Currently Autoprefixer version in terra-tool kit is 8.5.2 and this issue of adding prefixes for placeholder seems to be resolved with version 9.0.0

I also found similar ::placeholder prefix issue logged for Autoprefixer : https://github.com/postcss/autoprefixer/issues/1003 , but in the below conversation there is a comment which says this issue is with css minifier (Css Nano) : https://github.com/postcss/autoprefixer/issues/1003#issuecomment-372767209 
Css Nano having this issue while merging the styles for minifying and which seems to be resolved with PR : https://github.com/cssnano/cssnano/pull/480 (CSS Nano 4.0.0)

I was not able to find any reference of cssNano in terra-tool kit. Please let me know if there are any other configuration which I need to look into. 

I have tested that this prefixing issue does resolve with newer version of Autoprefixer,  @bjankord @neilpfeiffer  please let me know your thoughts on this issue.

**Comment by bjankord** [comment]
Nice work on looking into this. It does sound like its an issue with some of the tooling we use for generating the prefixes. My initial thoughts are we look into writing out the explicit vendor prefix needing for Microsoft browsers in our source code so it doesnt rely on autoprefixer if we haven't done that already.

We are planning to update the Autoprefixer version as part of the terra-toolkit v5 release.
Teams can get around this by using Autoprefixer v9 in their applications I believe.

**Comment by supreethmr** [comment]
Yes I tried adding Explicit vendor prefix for Microsoft browsers but adding vendor prefix throws style lint error : [selector-no-vendor-prefix](https://stylelint.io/user-guide/rules/selector-no-vendor-prefix/) 

I am not sure whether we can by pass this lint error. 

With this lint error I think having newer version of auto prefixer would resolve this issue instead of adding vendor prefix manually.

**Comment by bjankord** [comment]
We can disable the linter for this style and make a TODO note to remove this code once we update Autoprefixer to v9. We have [an issue logged in terra-toolkit to update Autoprefixer](https://github.com/cerner/terra-toolkit/issues/161) but it will be some time before we get to it.

I'm thinking something like this:
```scss
    /* TODO: Remove vendor prefix once we update to autoprefixer v9 */
    /* stylelint-disable selector-no-vendor-prefix */
    &::placeholder,
    &:-ms-input-placeholder {
      color: var(--terra-form-input-placeholder-color, #70787c);
      font-style: var(--terra-form-input-placeholder-font-style);
    }
    /* stylelint-enable selector-no-vendor-prefix */
```
