### ISSUE TITLE
Make terra base styles opt-in

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#2563]
# Feature Request

## Description
In terra-base, we have some styles that are currently global. These work great until they don't. Instead of keeping these global, we want to update these styles so they are opt-in if you want them to be applied.

https://github.com/cerner/terra-core/blob/master/packages/terra-base/src/Base.scss

**Comment by bjankord** [comment]
Talked about componentizing styles under a div. Should be able to do this for everything except for the html font-size. This needs to stay on html for rem units to work as we  intend.

**Comment by bjankord** [comment]
Looking through the base styles, this is what I'm currently thinking:

```scss
html {
  font-size: var(--terra-base-font-size, 87.5%); // needs to style html element for rem calculations to be predictable
  height: var(--terra-base-html-height, 100%); // needs to style html element for flexbox containers to work that need to fill the height of the page
  text-size-adjust: 100%; // Prevent adjustments of font size after orientation changes in iOS.
}

body {
  height: var(--terra-base-body-height, 100%); // needs to style body element for flexbox containers to work that need to fill the height of the page
  margin: var(--terra-base-body-margin, 0); // needs to style the body element to remove default browser style that adds margin to body element
}

/* Componentized CSS, only applies to terra-base and it's children */
.base {
  box-sizing: border-box;   // Normalize box-sizing. More info: https://css-tricks.com/box-sizing/#article-header-id-6
  color: var(--terra-base-color, #1c1f21);
  font-family: var(--terra-base-font-family, 'Helvetica Neue', Helvetica, Arial, sans-serif);
  font-size: 1rem;
  height: var(--terra-base-height, 100%);
  line-height: var(--terra-base-line-height, 1.4285714285714286);

  *,
  *::before,
  *::after {
    box-sizing: inherit;
  }

@media print {
    background-color: transparent !important;
    color: #000 !important;
  }
}

// If prop is set, apply this class to html element
.base-background {
  background-attachment: var(--terra-base-background-attachment);
  background-color: var(--terra-base-background-color, #fff);
  background-image: var(--terra-base-background-image);
  background-position: var(--terra-base-background-position);
  background-repeat: var(--terra-base-background-repeat);
  background-size: var(--terra-base-background-size);
}
```
Update terra-base to [render a div around it's children](https://github.com/cerner/terra-core/blob/master/packages/terra-base/src/Base.jsx#L83) and apply the .base class to the div.

For boolean props, we typically try to name them with `is` syntax and defaulting it to false.
I'm thinking of adding a prop named `isBackgroundStyleDisabled` to terra base that people could opt-out of the background style we'll apply to the html element.
