### ISSUE TITLE
[spike] Investigate our Theming Implementation

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-core#723]
# Issue Description
We currently have two approaches that we are looking into with doing our theming approach. There exist a [theme provider](https://github.com/cerner/terra-core/blob/theme-adapter/packages/terra-theme-provider/src/CSSVariableProvider.jsx#L29) branch that takes in a json file of attributes, and uses JavaScript to manually set the styles inside the current CSS. Another approach being investigated is using classes to set the variable names and swapping classes on the theming component to update the values. This approach can be viewed [here](https://www.google.com/search?q=theming+with+css+variables&rlz=1C5CHFA_enUS719US722&oq=theming+with+css+variables&aqs=chrome..69i57j69i60.4583j0j7&sourceid=chrome&ie=UTF-8)

The goal of this spike is to determine what we would like to do in order to implement theming. While we have talked about the two approaches logged up above, our team is open to other approaches that meets our needs as well.

We also should document what browser support we will have to dynamic theming as well. Older browsers don't support css variables, which can make some of our suggested implementations invalid.

**Comment by mhemesath** [comment]
I see a few ways to achieve this.

1. Each component contains all the 1st class themes.. This makes the theme provider do nothing more than flip a class name to activate a theme. To keep theme classes consistent.. we could use SASS mixins to ensure each component scopes the theme consistenly. e.g. The SASS mixin 

```css
// theme-mixins.sass
$default-theme: false !default
$bundled-themes: "consumer" "ocs"; !default

@mixin consumer-theme {
  @if index('consumer, $bundled-themes) {
    @if $default-theme == "consumer"
      .terra-consumer-theme {
        @content 
      }
    } @else {
      :root {
        @content 
      }
    }
  }  
}

@mixin ocs-theme {
  @if index('ocs, $bundled-themes) {
    @if $default-theme == "ocs"
      .terra-ocs-theme {
        @content 
      }
    } @else {
      :root {
        @content 
      }
    }
  } 
}


//=======================
// badge.sass

@include consumer-theme {
  --color: purple;
}

@include ocs-theme {
  --color: blue;
}

.badge {
  color: var(--color, black);
}
```
We can then set a sass variable in webpack to set default and bundled themes:

```js
{
    loader: "sass-loader",
    options: {
        data: "$default-theme: consumer; $bundled-themes: consumer"
    }
}
```
