### ISSUE TITLE
Update ThemeProvider to target html element to apply CSS custom property overrides

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#826]
# Issue Description
ThemeProvider works by rendering a `div` and applying a class which contains CSS custom properties. These properties are then applied to the `children` within the ThemeProvider.

```css
.cerner-clinical-theme {
  --terra-card-background-color: rgba(255, 255, 255, 0.8);
  --terra-card-box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.5);
 --terra-card-border: none;
}
```
Terra-base contains styles for the `html` and `body` elements which cannot be targeted as children of a ThemeProvider. 

To work around this limitation, we could use a prop to denote that a theme is a `root theme` and apply the theme class to the `html` element.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Using the `<ThemeProvider />` component, user should be able to alter theming variables targeting `html` and `body` elements.

## Current Behavior
Using the `<ThemeProvider />` component, user are unable alter theming variables targeting `html` and `body` elements as they don't render within `<ThemeProvider />`, avoiding the cascade of the custom property overrides applied by classes set in the `<ThemeProvider />`.
